reference: "/n/holylfs05/LABS/hopkins_lab/Lab/Phlox_resources/WG_assemblies/assemblies/pilosa/phlox_pilo.v1.fasta"
ref_org: "ppilo"
gap_bed: "/n/holylfs05/LABS/hopkins_lab/Everyone/felix_danielle_share/phlox_flye.v1.0.gaps.bed"
survivor_path: "/n/holylfs05/LABS/informatics/Users/dkhost/SURVIVOR-master/Debug/SURVIVOR"

#Don't change
intermediate_files: "results/intermediate_vcfs/"
